name:   'StayTune'
author: 'Bhavdip Pathar'
include:  ['_pages']
# Gems
gems: [jekyll-paginate]
paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
excerpt_separator: "{{ more }}"

safe:     false
markdown: 'kramdown'
timezone: 'America/Chicago'
highlighter: 'rouge'
disqus_shortname: StayTune
